# swiftlint rules
disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - line_length
  - redundant_nil_coalescing
  - todo
  - type_body_length
  - unused_optional_binding
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - fatal_error_message
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - yoda_condition
excluded:
  - Pods


# rules configuration
vertical_whitespace:
  max_empty_lines: 2
identifier_name:
  min_length: 2


# custom rules
custom_rules:
  import_definition_margin:
    included: ".*\\.swift"
    name: "Import Definition Margin"
    regex: "import [a-zA-Z]+\n\n?(class|struct|protocol|extension)"
    message: "Margin imports and definitions by two lines." # violation message. optional.
    severity: warning