# Uncomment the next line to define a global platform for your project
source 'https://github.com/Fiser33/iOSTiledViewerSpec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'IIIF Presenter' do
    pod 'iOSTiledViewer', :git => 'https://github.com/moravianlibrary/iOSTiledViewer.git', :branch => 'master'
    pod 'SDWebImage'
    pod 'CocoaLumberjack/Swift'
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Bond'
end
